### ISSUE TITLE
[Feature Request] - implement native interface to get resource list

### ISSUE THREAD

**Issue by zouyee** [kubernetes/dashboard#1881]
#### Issue details
implement native interface to get resource list
##### Environment

```
Dashboard version:
Kubernetes version:
Operating system:
Node.js version:
Go version:
```

##### Observed result

could not find the interface of resource list 
##### Expected result

`/_raw/{kind}/namespace/{namespace}` get resource list

**Comment by maciaszczykm** [comment]
Could you explain? Why do we need such thing?

**Comment by zouyee** [comment]
we have implemented these interfaces which could get the details of specified object that namespace scoped or namespace unscoped,but how to get the list of specified kind that namespace scoped or namespace unscoped?

**Comment by floreks** [comment]
I'm still not sure why do we need it. Where would we actually use it? Do you have any use case in mind to share with us?

I can understand the reason for generic delete, but raw list returns `runtime.Object` that we would need to cast or display as pure json text in frontend.

**Comment by maciaszczykm** [comment]
Please reopen after explaining use case for it.
