### ISSUE TITLE
log downloads from dashboards have wrong filename extention

### ISSUE THREAD

**Issue by akabdog** [kubernetes/dashboard#2631]
##### Environment
```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1
Kubernetes version: Kubernetes v1.8.2+coreos.0
Operating system: CentOS Linux release 7.4.1708 (Core)
Node.js version:
Go version:
Client: OSX 10.12.6 / Firefox 57
```

##### Steps to reproduce
Open kube dashboard -> pod -> logs -> download button. 
Filename is something like 'logs-from-service-scan-in-service-scan-6674cxxxxx-xxxxx.txt' 
Two problems here, there are quotes in the filename and the extension is .txt

##### Observed result
Opening the file in vim results in gibberish, must gunzip first.
The filename has quotes around it, this is unusual and annoying.

##### Expected result
Since the file that is download is a gzip file, the extension should be .gz or similar.
The filename should not have quotes around it.

##### Comments
i found the txt extension hardcoded in dashboard/src/app/backend/resource/container/logs.go but I don't know the implications of changing it.

**Comment by floreks** [comment]
I'll take a look at it today. Also what browser are you using? This is extremely important with this kind of issues.

**Comment by maciaszczykm** [comment]
> Filename is something like 'logs-from-service-scan-in-service-scan-6674cxxxxx-xxxxx.txt'
Two problems here, there are quotes in the filename and the extension is .txt

Please check with 1.8 if problem still exists. I remember that @cheld was fixing similar/same problem.

**Comment by floreks** [comment]
This was exactly the problem with Firefox and was fixed by https://github.com/kubernetes/dashboard/pull/2443. Use latest release 1.8.0.

**Comment by akabdog** [comment]
Thanks, I've tested the 1.8.0 dashboard and it did fix filename issue regarding quotes.
I'm still seeing something odd with firefox though, it appears to be gzipping the file but using the txt extension, for example:
```
$ head -n2 logs-from-service-user-in-service-user-595c5b745f-29h8c.txt
�&��D[�̳y�a�&�ݍF��x/�t�6���Q�i(y�f���DB��@_rj��S
                               �
                                <L�\�8)[�Y�P��t?腠�.� ��	���vf�_x����o�=<���2�q`��F.��1�a�4@�-I�~@�ox�P�%8��a�3���9��X�$��r�(T�2Nd�ғ@����P�H0��h�"��=�K4�l�����wz�#R��JH�P�B")�,�C�rG�G�� �w4a�N�n�����D�|}��s\@y�V��(���>�
                                                                                                                                                                                                                                      tG�����(u�a�}5�C�·RC�Z%q��C1���,�^n�9�RIƸ��16��m���61*fNM�4
                                                                                                                                                                                                                                                                                                 o�D��d��M��N!(I#�"r�w�EʔƄ�F4�b�
IҐv����^
gfdS�1Gv��9�&�XP~�ni ߜ�C�g���y��Q�߱�G��L�1r��e��!���A�
                                         ㄬb<%�~�h���e�RIB�O��tNx�|�pȖy
                                                                       .
$ mv logs-from-service-user-in-service-user-595c5b745f-29h8c.txt logs-from-service-user-in-service-user-595c5b745f-29h8c.gz
$ gunzip logs-from-service-user-in-service-user-595c5b745f-29h8c.gz
$ head -n2 logs-from-service-user-in-service-user-595c5b745f-29h8c
Using logging directory: './logs'
Using log file prefix: 'service-user-595c5b745f-29h8c-'
$
```
When downloading from chrome the .txt file opens as a regular text file:
```
$ head -n2 logs-from-service-user-in-service-user-595c5b745f-29h8c.txt
Using logging directory: './logs'
Using log file prefix: 'service-user-595c5b745f-29h8c-'
$
```

**Comment by akabdog** [comment]
@floreks should we reopen?

**Comment by floreks** [comment]
I am already working on a fix in #2647 for both this issue and #2640. Download will be completely redesigned.
