### ISSUE TITLE
Symlink old dashboard YAML to new?

### ISSUE THREAD

**Issue by mrichman** [kubernetes/dashboard#3448]
I just noticed that the "official" dashboard YAML URL was changed from `https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml` to `https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml`.

This change is going to break virtually every piece of documentation in existence.

Is there no way to symlink the old URL to the new?

**Comment by chriskinsman** [comment]
Even the kubernetes dashboard docs has inconsistently updated the link.  

i.e. this documentation page still links to the old yaml: https://github.com/kubernetes/dashboard/wiki/Installation

**Comment by thisLambo** [comment]
Just to add to this issue, the `kubernetes-dashboard.yaml` deploys the arm build of the Kubernetes Dashboard ( https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended/kubernetes-dashboard.yaml#L112 ) and the `kubernetes-dashboard-arm.yaml` deploys the amd64 build of Dashboard ( https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended/kubernetes-dashboard-arm.yaml#L111 ).

The -head.yaml files point to the correct architectures.

**Comment by GregSilverman** [comment]
@thisLambo, that would probably explain why I was getting a `CrashBackLoop` when trying to install!

**Comment by thisLambo** [comment]
> @thisLambo, that would probably explain why I was getting a `CrashBackLoop` when trying to install!

Sorry for deleting my reply on you, but I found the issue relating to the architecture: https://github.com/kubernetes/dashboard/issues/3447

**Comment by themightychris** [comment]
Y'all broke a ton of stuff in the world by moving this after promoting using that URL in shell commands to install

**Comment by maciaszczykm** [comment]
We have fixed most of the links to the old YAML location. I think we can close it right now.

/close

**Comment by Angha** [comment]
is the following 
 url 'https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml'  is  going  to  get  fixed?  still get  ERROR  404 
if  not, which is the official new  url  to use instead?

**Comment by themightychris** [comment]
If documentation is going to include URLs to yaml files, those URLs should be treated like contracts

Perhaps maintain a new branch called `deploy` that yaml files get published to on release with canonical paths e.g. `https://raw.githubusercontent.com/kubernetes/dashboard/deploy/recommended/kubernetes-dashboard.yaml`

**Comment by thedarkfalcon** [comment]
> We already updated the URLs and they are pointing to stable tagged branches that will not change.
What do you mean? The original link 404s still. These URLs were hardcoded into several scripts as per the documentation, I assumed they would always be valid. If these URLs start changing, its going to force devs to start saving a version that they know will always be available (thus start losing the benefits of always pulling the latest stable etc). As per @mrichman why isn't there a symbolic link?

**Comment by floreks** [comment]
It was explained why we have made such decision on the slack and in the #3451.

> We have promoted this way of installing Dashboard and it was our mistake which we have to finally resolve. The only way we can do that is to force people to use installation links that are not referring master branch in any way. It is not about the yaml files. It is about using links that rely directly on the unstable master branch instead of stable tagged branches. Master branch can always be changed in a way that might introduce breaking changes. That is why it is never a good idea to rely on it. We have learned our lesson and updated our documentation. All public documents should be forced to be updated also.

There are many reasons why we should not rely on the master branch and why should everyone that is using Dashboard on prod rely only on stable links, that will not change in the future. The decision to update an app should come from the user, it should not be silently forced by external changes. This is both a security and reliability issue.

**Comment by khushalkunjir** [comment]
> 
> 
> I just noticed that the "official" dashboard YAML URL was changed from `https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml` to `https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml`.
> 
> This change is going to break virtually every piece of documentation in existence.
> 
> Is there no way to symlink the old URL to the new?

Thanks its working

**Comment by Robson4** [comment]
Neither of these links work;

https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml to https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml

Does anyone have a working link for installing the Kubernetes dashboard?

Thanks

**Comment by floreks** [comment]
Did you look at the main repo page?

https://github.com/kubernetes/dashboard

**Comment by Robson4** [comment]
Thank Floreks, found the link here https://github.com/kubernetes/dashboard and it worked

**Comment by razz26** [comment]
Thanks Floreks, I too found the link here https://github.com/kubernetes/dashboard and it worked.

**Comment by EricoCartmanez** [comment]
`https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.4/aio/deploy/recommended.yaml`
