### ISSUE TITLE
Unable to access Kubernetes UI

### ISSUE THREAD

**Issue by likku3** [kubernetes/dashboard#349]
Please guide me to over come this error .
![kube-ui](https://cloud.githubusercontent.com/assets/16572724/12948231/b7866128-d026-11e5-9350-4edd2c761bf4.jpg)

**Comment by bryk** [comment]
AFAIU Dashboard cannot talk with your master. Do you have any security restrictions for talking with the master?

**Comment by likku3** [comment]
I am Sorry ,I didn't got your question.My master server is deployed in AWS  and i am trying to access the dashboard from my local machines.Please let me know if you need any details from the master and remaining nodes.

**Comment by bryk** [comment]
Can you attach logs from the Dashboard? Find pod name with `kubectl get pods --namespace=kube-system` and then `kubectl logs <pod name> --namespace=kube-system`.

**Comment by likku3** [comment]
core@master ~ $ ./kubectl get pods --namespace=kube-system
NAME                                READY     STATUS    RESTARTS   AGE
kubernetes-dashboard-v0.1.0-x6l5a   1/1       Running   0          1h


core@master ~ $ ./kubectl logs kubernetes-dashboard-v0.1.0-x6l5a --namespace=kube-system
2016/02/10 12:16:54 Starting HTTP server on port 9090
2016/02/10 12:16:54 Creating API client for 
ERROR: logging before flag.Parse: E0210 12:16:54.206434       1 helper.go:332] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
2016/02/10 12:16:54 Creating Heapster REST client for http://10.100.0.1:443/api/v1/proxy/namespaces/kube-system/services/heapster/api
2016/02/10 12:17:46 Incoming HTTP/1.1 GET /api/replicationcontrollers request from 10.244.77.0:47298
2016/02/10 12:17:46 Getting list of all replication controllers in the cluster
2016/02/10 12:17:46 Get https://10.100.0.1:443/api/v1/replicationcontrollers: x509: failed to load system roots and no roots provided
2016/02/10 12:17:46 Outcoming response to 10.244.77.0:47298 with 500 status code

**Comment by bryk** [comment]
@cheld @floreks Have you ever seen this?

**Comment by bryk** [comment]
https://groups.google.com/forum/#!topic/google-containers/pSEUOcWNUbc

**Comment by bryk** [comment]
What's your cluster master version?

**Comment by floreks** [comment]
I haven't encountered this error before. It looks like some salt problem or version mismatch.

**Comment by likku3** [comment]
No,This is my first time installation of k8s in lab environment.Master cluster version is v1.0.3.

**Comment by floreks** [comment]
I think our minimum supported version is 1.1? @bryk am I correct?

**Comment by likku3** [comment]
It's a version mismatch ,able to solve the issue.Thanks for your help floreks and bryk

**Comment by geoand** [comment]
Greetings, I am seeing this exact same issue (even have the same ouptput from `kubectl logs <pod-name> --namespace=kube-system` ).
I have deployed the cluster on bare-metal CentOS machines.

The difference is that I am running Kubernetes 1.2.0 
(the output from `kubectl version` is 
`Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}`

`Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
`)

The replication I am using to bring up the dashboard is 
```
apiVersion: v1
kind: ReplicationController
metadata:
  # Keep the name in sync with image version and
  # gce/coreos/kube-manifests/addons/dashboard counterparts
  name: kubernetes-dashboard-v1.0.0
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.0
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
```

I also tried the solution of deleting the secret mentioned in #374, but with no luck, the problem persists.
Moreover the result of running 
```
$ DEFAULT_TOKEN=$(kubectl --namespace=kube-system get serviceaccount default -o jsonpath="{.secrets[0].name}")
$ TOKEN_VALUE=$(kubectl --namespace=kube-system get secret "$DEFAULT_TOKEN" -o go-template="{{.data.token}}" | base64 -d)
$ curl -k -H "Authorization: Bearer $TOKEN_VALUE" https://my-api-server:6443/version
```
is 
```
{
  "major": "1",
  "minor": "2",
  "gitVersion": "v1.2.0",
  "gitCommit": "5cb86ee022267586db386f62781338b0483733b3",
  "gitTreeState": "clean"
}
```

Do you have in mind any additional things I could try?

**Comment by geoand** [comment]
I got it to work by adding  `args: ["--apiserver-host", "http://my-ip:8080"]` to the replication controller definition

**Comment by bryk** [comment]
I think you still have problems with your cluster setup, but glad that something worked.

**Comment by geoand** [comment]
I'm sure you are correct, and there are deeper issues with my cluster.
Thanks!

**Comment by junsaw** [comment]
Hey All, 

I am also experiencing the same issue, any help will be appreciated. 

**Error Message from the Web Page:** 

Internal Server Error (500)

the server could not find the requested resource (get namespaces)


**Error Logs from the dashboard Pod:**

Application configuration {"serverTime":1473829033645}
[2016-09-14T04:57:15Z] Incoming HTTP/1.1 GET /api/v1/workload/default?itemsPerPage=10&page=1 request from 192.168.58.0:42842
Getting lists of all workloads
the server could not find the requested resource (get pods)
[2016-09-14T04:57:15Z] Outcoming response to 192.168.58.0:42842 with 500 status code
[2016-09-14T04:57:15Z] Incoming HTTP/1.1 GET /api/v1/workload/default?itemsPerPage=10&page=1 request from 192.168.58.0:42842
Getting lists of all workloads
the server could not find the requested resource (get pods)
[2016-09-14T04:57:15Z] Outcoming response to 192.168.58.0:42842 with 500 status code
[2016-09-14T04:57:16Z] Incoming HTTP/1.1 GET /api/v1/workload/default?itemsPerPage=10&page=1 request from 192.168.58.0:42842
Getting lists of all workloads
the server could not find the requested resource (get replicationControllers)
[2016-09-14T04:57:16Z] Outcoming response to 192.168.58.0:42842 with 500 status code
[2016-09-14T04:57:16Z] Incoming HTTP/1.1 GET /api/v1/workload/default?itemsPerPage=10&page=1 request from 192.168.58.0:42842
Getting lists of all workloads

**Comment by bryk** [comment]
What is your cluster version?

**Comment by junsaw** [comment]
kubectl version

Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"ec7364b6e3b155e78086018aa644057edbe196e5", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"ec7364b6e3b155e78086018aa644057edbe196e5", GitTreeState:"clean"}

**Comment by junsaw** [comment]
Any update on this request ..... 

Any help will be appreciated.

**Comment by IanLewis** [comment]
@junsaw I think this is the same issue as on #1286 ? Could we close this issue in favor of that one?

**Comment by bryk** [comment]
Yes, makes sense.
