### ISSUE TITLE
Panic: Initializing csrf token from kubernetes-dashboard-csrf secret

### ISSUE THREAD

**Issue by feliperyan** [kubernetes/dashboard#4938]
##### Environment

Installation method:
K3S

Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:07:30Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/arm"}
```

Dashboard version:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc5/aio/deploy/recommended.yaml
```

Operating system:
`Raspbian Buster`

##### Steps to reproduce
Installed Dashboard by applying yaml file available at https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc5/aio/deploy/recommended.yaml

##### Observed result
```
k logs kubernetes-dashboard-866f987876-lv4jw --namespace kubernetes-dashboard
2020/02/23 03:53:12 Starting overwatch
2020/02/23 03:53:12 Using namespace: kubernetes-dashboard
2020/02/23 03:53:12 Using in-cluster config to connect to apiserver
2020/02/23 03:53:12 Using secret token for csrf signing
2020/02/23 03:53:12 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: Get https://10.43.0.1:443/api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-csrf: dial tcp 10.43.0.1:443: i/o timeout       
goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0x3c0d9c0)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:40 +0x300
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:65
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0x3d0c900)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:494 +0xac
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0x3d0c900)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:462 +0x34
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:543
main.main()
        /home/travis/build/kubernetes/dashboard/src/app/backend/dashboard.go:105 +0x1c4
```

##### Expected result
Dashboard accessible 

##### Comments
Could the new GO version have caused this?

**Comment by feliperyan** [comment]
Closing: I have no idea why but a whole cluster reboot fixed the issue.

**Comment by shridharkute** [comment]
This could be the problematic worker node where pods/containers were created. 

it solved for me when i recreated the pods after sutting down the problematc worker node.

**Comment by nicolasps** [comment]
This issue is still not solve. Please reopen 

Trying to deploy: https://github.com/kubernetes/dashboard/blob/master/aio/deploy/alternative.yaml using a different namespace as kubernetes-dashboard will throw:

```
2021/03/17 08:37:12 Initializing csrf token from kubernetes-dashboard-csrf secret                                                                                                                                                             
panic: secrets "kubernetes-dashboard-csrf" not found                                                                   

goroutine 1 [running]:                                     
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc0001595a0)                                                                                                                                            
        /home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:41 +0x413                                                                                                                                                
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)                                                                                                                                                          
        /home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:66                                                                                                                                                       
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc0001b8880)                                                                                                                                             
        /home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:503 +0xc6                                                                                                                                                     
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc0001b8880)                                                                                                                                                    
        /home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:471 +0x47                                                                                                                                                     
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)                                                                                                                                                                  
        /home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:552                                                                                                                                                           
main.main()
```

Using:
- kubernetes v1.20.4
- dashboard: kubernetesui/dashboard:v2.2.0

**Comment by floreks** [comment]
I don't see any configuration here. From our side it was fixed.

https://github.com/kubernetes/dashboard/blob/570ff985b70aa1b7297a7a1d2377123eac4c537f/src/app/backend/client/csrf/manager.go#L34-L42

The namespace name is taken from the argument passed to the dashboard.

**Comment by nicolasps** [comment]
Unfortunately,  despite the fix the issue is still happening.

Changing the namespace value (for example from "kubernetes-dashboard" to "othernamespace") in all possible places of the file https://github.com/kubernetes/dashboard/blob/master/aio/deploy/alternative.yaml will throw the error 

`panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:othernamespace:kubernetes-dashboard" cannot get resource "secrets" in API group "" in the namespace "kubernetes-dashboard"`

For an unknown reason, it tries to get the secret  "kubernetes-dashboard-csrf" from the namespace "kubernetes-dashboard" although the application was deployed on "othernamespace"

I kindly invite you to reproduce the error.

**Comment by floreks** [comment]
Did you update the `namespace` argument of the dashboard container?

https://github.com/kubernetes/dashboard/blob/06e7fac1b78727e07c0dd7b693279d13b4914b48/aio/deploy/alternative.yaml#L178-L185

**Comment by nicolasps** [comment]
No, I didn't. 

After updating the namespace argument Dashboard could be successfully deployed in the aimed namespace.

Thank you for your support @floreks

**Comment by gcOssi** [comment]
Hi,
Please tell me, you updating the namespace from "kubernetes-dashboard" to "Dashboard"??
